momo.partnerCode=MOMO
momo.accessKey=F8BBA842ECF85
momo.secretKey=K951B6PE1waDMi640xX08PD3vg6EkVlz
momo.endpoint=https://test-payment.momo.vn/v2/gateway/api/create
momo.returnUrl=http://localhost:5000/TravelBookingApp
momo.notifyUrl=https://oxidation-untold-tighten.ngrok-free.dev/TravelBookingApp/api/momo/ipn