momo.partnerCode=MOMO
momo.accessKey=F8BBA842ECF85
momo.secretKey=K951B6PE1waDMi640xX08PD3vg6EkVlz
momo.endpoint=https://test-payment.momo.vn/v2/gateway/api/create
momo.returnUrl=http://localhost:5000/TravelBookingApp
momo.notifyUrl=https://oxidation-untold-tighten.ngrok-free.dev/TravelBookingApp/api/momo/ipn

paypal.mode=sandbox
paypal.clientId=AWuXaji91ZBIHvYz2bUCt2eSVWs_bBPETzVj4huU2KeiDrE32XoDvh1PUQ2FQxuZ9iW2mINxtzyFFs-z
paypal.clientSecret=EEM3Grc7VupTqDHhdJLuxrkNlvwapTSHfBF5Nw-j6OE9X3ERjPgTYvajwliwKfCypmQ4teXqanu3VktH
momo.returnUrl=http://localhost:5000/TravelBookingApp/success
momo.cancelUrl=http://localhost:5000/TravelBookingApp/cancel
